services:
  # Backend API Service
  - type: web
    name: tone-picker-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MISTRAL_API_KEY
        sync: false
      - key: PORT
        value: 10000

  # Frontend Web Service
  - type: web
    name: tone-picker-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tone-picker-backend.onrender.com/api
